version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: t3codescommanders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=t3codescommanders
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DEBUG=True
      - SECRET_KEY=django-insecure-development-key
    depends_on:
      - db

volumes:
  postgres_data: 